services:
  ginwalkers-frontend:
    build: .
    ports:
      - '443:443'
    volumes:
      - /home/linux/ssl/ginwalkers:/etc/ssl/ginwalkers:ro
    networks:
      - swgoh-comlink

networks:
  swgoh-comlink:
    external: true
